syntax = "proto3";

package profile;

import "google/protobuf/wrappers.proto";

option java_multiple_files = true;
option java_package = "com.techpassport.grpc.profile";
option java_outer_classname = "ProfileServiceProto";

service ProfileService {
  rpc CreateProfile(Request) returns (Response);
}

message Request {
  string user_id = 1;
  google.protobuf.StringValue first_name = 2;
  google.protobuf.StringValue last_name = 3;
  google.protobuf.StringValue avatar = 4;
  google.protobuf.StringValue phone = 5;
  google.protobuf.StringValue bio = 6;
}

message Response {
  string profile_id = 1;
}